# Generated by Django 2.1.7 on 2019-03-05 08:57

from django.db import migrations
from django.contrib.auth.models import Group, Permission


class Migration(migrations.Migration):

    def add_groups(apps, schema_editor):
        user_group = Group()
        user_group.name = "User"
        user_group.save()
        admin_group = Group()
        admin_group.name = "Admin"
        admin_group.save()
        for p in Permission.objects.all():
            admin_group.permissions.add(p)
        admin_group.save()

        pass

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_groups),
    ]
